/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123557-g106616f13d-20260319"
#endif /* AVUTIL_FFVERSION_H */
